import {loadCMS} from './cms.js';import {$,esc,todayName,first} from './utils.js';import {dutyCard,showDuty} from './duty.js';import {renderEvents} from './events.js';import {renderTabs,renderApps} from './apps.js';import {renderTalent} from './talent.js';import {openModal} from './modal.js';
let CMS={};
function greeting(){const h=new Date().getHours();return h<12?'Buenos días':h<19?'Buenas tardes':'Buenas noches'}
function renderStats(){const activeEvents=(CMS.eventos||[]).length, apps=(CMS.links||[]).length, tbw=(CMS.tbw||[]).length, altas=(CMS.bt||[]).length+(CMS.ss||[]).length;$('#stats').innerHTML=`<div class="stat"><strong>${tbw}</strong><span>TBW</span></div><div class="stat"><strong>${altas}</strong><span>Altas</span></div><div class="stat"><strong>${apps}</strong><span>Links</span></div><div class="stat"><strong>${activeEvents}</strong><span>Eventos</span></div>`}
function renderToday(){const day=todayName();const sem=(CMS.semanales||[]).find(x=>String(first(x,['Frecuencia'])).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'')===day.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,''));const cards=[dutyCard(CMS),`<article class="card" data-open="wfm"><span class="icon">${esc(first(sem||{},['Icono'])||'📅')}</span><h3>${esc(first(sem||{},['Actividad'])||'Mejora continua')}</h3><p>${esc(first(sem||{},['Descripción','Descripcion'])||'Qué hacer hoy, qué vence y qué acceso necesitas.')}</p><span class="badge">${esc(day)}</span></article>`,`<article class="card"><span class="icon">🎯</span><h3>Mejora continua</h3><p>Revisa checks, eventos y herramientas clave del día.</p><span class="badge">NextGen</span></article>`];$('#todayCards').innerHTML=cards.join('')}
function renderDaily(){const el=$('#dailyChecks');el.innerHTML=(CMS.diarias||[]).filter(x=>String(first(x,['Visible'])).toUpperCase()!=='FALSE').sort((a,b)=>(+first(a,['Prioridad'])||9)-(+first(b,['Prioridad'])||9)).map(x=>`<div class="check-item"><span class="checkmark">✓</span><div><h3>${esc(first(x,['Icono']))} ${esc(first(x,['Actividad']))}</h3><p>${esc(first(x,['Descripción','Descripcion']))}</p></div></div>`).join('')}
function showWFM(){const w=(CMS.wfm||[])[0]||{};openModal(`<span class="eyebrow">Regla WFM</span><h2>Kronos WFM</h2><div class="modal-list"><div class="item">${esc(Object.values(w).join('
')).replace(/
/g,'<br>')}</div></div>`)}
function bind(){document.body.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(!o)return;if(o.dataset.open==='duty')showDuty(CMS);if(o.dataset.open==='wfm')showWFM()});$('#searchInput').addEventListener('input',e=>renderApps(CMS,e.target.value));$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';renderApps(CMS,'')})}
async function init(){CMS=await loadCMS();$('#todayLabel').textContent=new Date().toLocaleDateString('es-MX',{weekday:'long',day:'2-digit',month:'long'});$('#greeting').textContent=`${greeting()}, Enrique`;renderStats();renderToday();renderDaily();renderEvents(CMS);renderTalent(CMS);renderTabs(CMS);renderApps(CMS);bind();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});let p;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();p=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(p){p.prompt();p=null;$('#installBtn').classList.add('hidden')}})}
init();
