import { esc, first, toDate, normalize } from './utils.js';
import { openModal } from './modal.js';
const monthNames = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
let state = { month:'Todos', type:'Todos' };
export function eventUrl(e){ const direct = first(e,['URL','Url','Liga','Vínculo','Vinculo']); if (direct) return String(direct).trim(); const ctx = first(e,['Contexto / Recordatorio','Contexto','Descripción','Descripcion']); const m = String(ctx||'').match(/https?:\/\/\S+/); return m ? m[0].trim() : ''; }
export function eventType(e){ const txt = normalize(`${first(e,['Actividad'])} ${first(e,['Contexto / Recordatorio','Contexto','Descripción','Descripcion'])}`); if(txt.includes('precios_maquila')) return 'Informativo'; if(txt.includes('autoica') || txt.includes('ica')) return 'AutoICA'; if(txt.includes('pagos especiales') || txt.includes('qna')) return 'Nómina'; if(txt.includes('corte de nomina') || txt.includes('nomina')) return 'Nómina'; if(txt.includes('campana') || txt.includes('summer') || txt.includes('platform') || txt.includes('rewards') || txt.includes('promocion')) return 'Campañas'; if(txt.includes('attensi') || txt.includes('recertificacion') || txt.includes('webinar') || txt.includes('seminario') || txt.includes('mujeres')) return 'Capacitación'; if(txt.includes('coffee') || txt.includes('cafe')) return 'Coffee'; if(txt.includes('inventario') || txt.includes('pin pad') || txt.includes('tpv')) return 'Inventarios'; if(txt.includes('talent') || txt.includes('best talent')) return 'Talent'; return 'Otros'; }
export function allEvents(cms){ return (cms.eventos||[]).map(e=>{ const start=toDate(first(e,['Fecha Inicio','Inicio'])); const end=toDate(first(e,['Fecha Fin','Fin'])||first(e,['Fecha Inicio','Inicio']), true); return {e,start,end,type:eventType(e)}; }).filter(x=>x.start && x.end && x.end.getFullYear()>1901).sort((a,b)=>a.start-b.start || a.end-b.end); }
export function normalizeEvents(cms){ const today=new Date(); today.setHours(0,0,0,0); return allEvents(cms).filter(x=>x.end>=today && x.type!=='Informativo'); }
export function currentEvents(cms){ const now=new Date(); return allEvents(cms).filter(x=>x.start<=now && x.end>=now && x.type!=='Informativo'); }
export function currentInfo(cms){ const now=new Date(); return allEvents(cms).filter(x=>x.start<=now && x.end>=now && x.type==='Informativo'); }
function labelFor(start,end,today){ if(today>=start&&today<=end) return ['Vigente','active']; return ['Programado','future']; }
function dateRange(start,end){ const fmt=x=>x.toLocaleDateString('es-MX',{day:'2-digit',month:'short'}).replace('.',''); return fmt(start)+(start.toDateString()!==end.toDateString()?` – ${fmt(end)}`:''); }
function linkLabel(e){ return first(e,['Link','Texto Link','Acción','Accion']) || 'Abrir liga'; }
function imagePath(e){ const img = first(e,['ImagenDetalle','Imagen Detalle','Foto','ImagenArchivo']); return img ? `assets/photos/${img}` : ''; }
function isPayroll(e){ return normalize(first(e,['Actividad'])).includes('corte de nomina'); }
export function payrollCritical(cms){ const now=new Date(); const today=new Date(now); today.setHours(0,0,0,0); for(const row of allEvents(cms).filter(x=>isPayroll(x.e))){ const endDay=new Date(row.end); endDay.setHours(0,0,0,0); if(today.getTime()===endDay.getTime() && now.getHours()<9) return {kind:'today',row}; const startDay=new Date(row.start); startDay.setHours(0,0,0,0); if(today.getTime()===startDay.getTime()) return {kind:'active',row}; } return null; }
function payrollAlert(start,end,today){ const now=new Date(); const endDay = new Date(end); endDay.setHours(0,0,0,0); if(today.getTime()===endDay.getTime() && now.getHours()<9) return `<div class="payroll-alert today"><strong>🚨 Hasta las 09:00 AM</strong><span>Después desaparece automáticamente.</span></div>`; return ''; }
function eventCard({e,start,end,type},today){ const [label,cls]=labelFor(start,end,today); const url = eventUrl(e); const img = imagePath(e); const imageBtn = img ? `<button class="details-link" data-image="${esc(img)}">Ver imagen</button>` : ''; const linkBtn = url ? `<a class="details-link event-link" href="${esc(url)}" target="_blank" rel="noopener">${esc(linkLabel(e))}</a>` : ''; const ctx = first(e,['Contexto / Recordatorio','Contexto','Descripción','Descripcion']); return `<article class="event ${cls}" data-type="${esc(type)}"><span class="event-icon">${esc(first(e,['Imagen','Icono'])||'📌')}</span><div><div class="event-top"><h4>${esc(first(e,['Actividad']))}</h4><small>${esc(label)}</small></div><p>${esc(String(ctx).split('\n')[0])}</p><div class="event-meta"><small>${esc(dateRange(start,end))}</small><small>${esc(type)}</small>${imageBtn}${linkBtn}</div>${isPayroll(e)?payrollAlert(start,end,today):''}</div></article>`; }
function renderFilterButtons(cms, rootId='eventFiltersMini', compact=true){ const rows=normalizeEvents(cms); const months=['Todos',...new Set(rows.map(x=>monthNames[x.start.getMonth()]))]; const types=['Todos','AutoICA','Campañas','Nómina','Capacitación','Coffee','Inventarios','Talent','Otros']; const root=document.getElementById(rootId); if(!root) return; root.innerHTML=`<select class="filter-select" data-event-month>${months.map(m=>`<option ${m===state.month?'selected':''}>${esc(m)}</option>`).join('')}</select>${compact?'':`<select class="filter-select" data-event-type>${types.map(t=>`<option ${t===state.type?'selected':''}>${esc(t)}</option>`).join('')}</select>`}`; root.onchange=e=>{ if(e.target.matches('[data-event-month]')) state.month=e.target.value; if(e.target.matches('[data-event-type]')) state.type=e.target.value; renderEvents(cms); }; }
function filteredRows(cms){return normalizeEvents(cms).filter(x=>{const m=monthNames[x.start.getMonth()]; return (state.month==='Todos'||state.month===m) && (state.type==='Todos'||state.type===x.type);});}
export function nextEvent(cms){ return normalizeEvents(cms)[0] || null; }
export function renderEvents(cms){ const today=new Date(); today.setHours(0,0,0,0); renderFilterButtons(cms,'eventFiltersMini',true); const rows=filteredRows(cms).slice(0,16); const grouped={active:[],future:[]}; rows.forEach(x=>grouped[labelFor(x.start,x.end,today)[1]].push(x)); const groupTitle={active:'🔥 Vigentes',future:'🗓️ Agenda'}; document.getElementById('events').innerHTML=Object.entries(grouped).filter(([,arr])=>arr.length).map(([k,arr])=>`<div class="event-group"><h3>${groupTitle[k]}</h3>${arr.map(x=>eventCard(x,today)).join('')}</div>`).join('') || '<p class="muted">Sin eventos configurados.</p>'; }
export function renderEventsModal(cms){ const today=new Date(); today.setHours(0,0,0,0); const rows=normalizeEvents(cms); const months=['Todos',...new Set(rows.map(x=>monthNames[x.start.getMonth()]))]; const types=['Todos','AutoICA','Campañas','Nómina','Capacitación','Coffee','Inventarios','Talent','Otros']; openModal(`<span class="eyebrow">Agenda</span><h2>📌 Agenda</h2><div class="filter-row modal-filters"><select class="filter-select" id="modalEventMonth">${months.map(m=>`<option ${m===state.month?'selected':''}>${esc(m)}</option>`).join('')}</select><select class="filter-select" id="modalEventType">${types.map(t=>`<option ${t===state.type?'selected':''}>${esc(t)}</option>`).join('')}</select></div><div id="modalEventsList" class="event-list full-events"></div>`); const paint=()=>{state.month=document.getElementById('modalEventMonth').value; state.type=document.getElementById('modalEventType').value; document.getElementById('modalEventsList').innerHTML=filteredRows(cms).map(x=>eventCard(x,today)).join('') || '<p class="muted">Sin eventos con ese filtro.</p>'; renderEvents(cms);}; document.getElementById('modalEventMonth').onchange=paint; document.getElementById('modalEventType').onchange=paint; paint(); }
